stages: 
  - deploy

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - gem install faraday -v 2.3.0
    - ls
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only: 
  - main
